# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 08:58
from __future__ import unicode_literals

import analysis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_file', models.FileField(upload_to=analysis.models.change_file_name, verbose_name='Analysis file')),
            ],
        ),
    ]
